name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # or your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Specify your PHP version
          extensions: mbstring, xml, bcmath, curl

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Run Tests
        run: php artisan test

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job is complete before deploying
    if: github.ref == 'refs/heads/main'  # Only deploy from the main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        run: |
          ssh user@yourserver.com << 'EOF'
            cd /path/to/your/project
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            exit
          EOF
